INTENT_CLASSIFY_MODEL = "llama3-8b-8192"

CATEGORY_GENERAL = "general"
CATEGORY_REALTIME = "realtime"
CATEGORY_CAMERA = "camera"
CATEGORY_MIXED = "mixed"
CATEGORY_TASK = "task"

INTENT_CHAT = "chat"
INTENT_CAMERA = "camera"
INTENT_OPEN_WEBCAM = "open_webcam"
INTENT_CLOSE_WEBCAM = "close_webcam"
INTENT_GENERATE_IMAGE = "generate_image"
INTENT_PLAY = "play"
INTENT_CONTENT = "content"
INTENT_YOUTUBE_SEARCH = "youtube_search"
INTENT_GOOGLE_SEARCH = "google_search"
INTENT_OPEN = "open"

HEAVY_INTENTS = [INTENT_GENERATE_IMAGE]

INSTANT_INTENTS = [
    INTENT_OPEN,
    INTENT_PLAY,
    INTENT_CAMERA,
    INTENT_OPEN_WEBCAM,
    INTENT_CLOSE_WEBCAM,
    INTENT_GOOGLE_SEARCH,
    INTENT_YOUTUBE_SEARCH,
    INTENT_CONTENT,
]

ROUTE_TO_INTENT = {
    "open": INTENT_OPEN,
    "play": INTENT_PLAY,
    "camera": INTENT_CAMERA,
    "open_webcam": INTENT_OPEN_WEBCAM,
    "close_webcam": INTENT_CLOSE_WEBCAM,
    "generate_image": INTENT_GENERATE_IMAGE,
    "content": INTENT_CONTENT,
    "google_search": INTENT_GOOGLE_SEARCH,
    "youtube_search": INTENT_YOUTUBE_SEARCH,
    "general": INTENT_CHAT,
    "realtime": INTENT_CHAT,
}
